# Generated by Django 5.1.1 on 2024-10-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodb',
            name='direccion_1',
            field=models.CharField(max_length=255, verbose_name='Dirección 1'),
        ),
    ]
