# Generated by Django 5.1.1 on 2024-10-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodb',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuariodb',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuariodb',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
