# Generated by Django 5.1.1 on 2024-10-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodb',
            name='visitas',
            field=models.PositiveIntegerField(default=0, verbose_name='Visitas'),
        ),
    ]

