# Generated by Django 5.1.1 on 2024-11-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productodb',
            name='categoria_fk',
        ),
        migrations.AlterField(
            model_name='categoriadb',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la categoría'),
        ),
    ]
