# Generated by Django 5.1.1 on 2024-10-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodb',
            name='direccion_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección 1'),
        ),
        migrations.AddField(
            model_name='productodb',
            name='municipio_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.municipiodb', verbose_name='Municipio'),
        ),
        migrations.CreateModel(
            name='SubcategoriaDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la subcategoría')),
                ('categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.categoriadb')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
            },
        ),
    ]
