# Generated by Django 5.1.1 on 2024-10-25 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodb',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuariodb',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="El número debe estar en el formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono'),
        ),
    ]
