# Generated by Django 5.1.1 on 2024-10-29 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_usuariodb_direccion_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoriaDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la subcategoría')),
                ('categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='sistema.categoriadb')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
            },
        ),
    ]
