# Generated by Django 5.1.1 on 2024-10-31 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_listafavoritosdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodb',
            name='direccion_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuariodb',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='perfil/perfil.png', null=True, upload_to='perfil/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='usuariodb',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="El número debe estar en el formato: '+59199999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de celular'),
        ),
    ]
