# Generated by Django 5.1.1 on 2024-10-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_pagodb_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagodb',
            name='imagen',
        ),
        migrations.AddField(
            model_name='productodb',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
