# Generated by Django 5.1.1 on 2024-10-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_productodb_direccion_1_productodb_municipio_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodb',
            name='subcategoria_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.subcategoriadb', verbose_name='Subcategoría'),
        ),
    ]
