# Generated by Django 5.1.1 on 2024-10-03 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_pagodb_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagodb',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='productodb',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenProductoDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenProduc', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('producto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='sistema.productodb')),
            ],
            options={
                'verbose_name': 'Imagen del Producto',
                'verbose_name_plural': 'Imágenes del Producto',
                'db_table': 'imagenes_productos',
            },
        ),
    ]
