# Generated by Django 5.1.1 on 2024-10-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_usuariodb_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodb',
            name='direccion_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Dirección 1'),
        ),
        migrations.AlterField(
            model_name='usuariodb',
            name='nombre_completo',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre completo'),
        ),
    ]
