# Generated by Django 5.1.1 on 2024-10-04 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_remove_productodb_imagen_productimagendb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProductoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('producto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='sistema.productodb')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
            },
        ),
        migrations.DeleteModel(
            name='ProductImagenDB',
        ),
    ]
