# Generated by Django 5.1.1 on 2024-10-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_productodb_visitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodb',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
