# Generated by Django 5.1.1 on 2024-11-16 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_categoriadb_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productodb',
            name='precio',
        ),
        migrations.AddField(
            model_name='productodb',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible para la venta'),
        ),
        migrations.AddField(
            model_name='productodb',
            name='precio_original',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99999.9)], verbose_name='Precio Original'),
        ),
    ]
