# Generated by Django 5.1.1 on 2024-11-12 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_remove_productodb_categoria_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productodb',
            name='subcategoria_fk',
        ),
        migrations.AddField(
            model_name='productodb',
            name='categoria_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.categoriadb'),
        ),
    ]
