# Generated by Django 5.1.1 on 2024-10-27 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_usuariodb_direccion_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodb',
            name='direccion_2',
        ),
        migrations.RemoveField(
            model_name='usuariodb',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='usuariodb',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='perfil/perfil.png', null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='usuariodb',
            name='nombre_completo',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='usuariodb',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="El número debe estar en el formato: '+59199999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono'),
        ),
    ]
