# Generated by Django 5.1.1 on 2024-10-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_remove_pagodb_imagen_remove_productodb_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodb',
            name='visitas',
            field=models.PositiveIntegerField(default=0, verbose_name='Visitas'),
        ),
    ]
