# Generated by Django 5.1.1 on 2024-10-29 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_subcategoriadb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodb',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productodb',
            name='municipio_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.municipiodb'),
        ),
    ]
