# Generated by Django 5.1.1 on 2024-11-16 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_remove_productodb_precio_productodb_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productodb',
            name='precio_original',
        ),
        migrations.AddField(
            model_name='productodb',
            name='precio',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99999.9)], verbose_name='Precio Original'),
            preserve_default=False,
        ),
    ]
