# Generated by Django 5.1.1 on 2024-10-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_productodb_subcategoria_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodb',
            name='direccion_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuariodb',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='perfil/perfil.png', null=True, upload_to='perfil/', verbose_name='foto de perfil'),
        ),
    ]
