# Generated by Django 5.1.1 on 2024-11-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_usuariodb_direccion_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodb',
            name='bloqueo_password_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariodb',
            name='intentos_fallidos_password',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productodb',
            name='detalle',
            field=models.TextField(max_length=500, verbose_name='Detalle'),
        ),
    ]
