# Generated by Django 5.1.1 on 2024-11-16 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_remove_productodb_precio_original_productodb_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodb',
            name='precio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99999.9)], verbose_name='Precio'),
        ),
    ]
