# Generated by Django 5.1.1 on 2024-10-30 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_productodb_direccion_alter_productodb_municipio_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaFavoritosDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='sistema.productodb')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='sistema.usuariodb')),
            ],
            options={
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
