# Generated by Django 5.1.1 on 2024-11-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alter_productodb_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraTransaccionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10, verbose_name='Tipo de transacción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de transacción')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles adicionales')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.productodb', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.usuariodb', verbose_name='Usuario relacionado')),
            ],
            options={
                'verbose_name': 'Bitácora de Transacción',
                'verbose_name_plural': 'Bitácoras de Transacciones',
            },
        ),
    ]
