# Generated by Django 5.1.1 on 2024-11-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alter_productodb_precio'),
    ]

    operations = [
    ]
