# Generated by Django 5.1.1 on 2024-11-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_transaccion_delete_bitacoratransacciondb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodb',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='sistema.productodb'),
        ),
    ]
