# Generated by Django 5.1.1 on 2024-11-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_alter_transaccion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.usuariodb'),
        ),
    ]
