# Generated by Django 4.2.7 on 2024-11-26 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_alter_transaccion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodb',
            name='departamento_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.departamentodb', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='productodb',
            name='provincia_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.provinciadb', verbose_name='Provincia'),
        ),
    ]
